#!/usr/bin/env python3
"""Generate all 5 missing audit pages for Archibald Titan."""
import os

BASE = "/home/ubuntu/archibald-titan-ai/client/src/pages"

# ─────────────────────────────────────────────────────────────────────────────
# 1. SECURITY PAGE
# ─────────────────────────────────────────────────────────────────────────────
security_page = '''import { useState } from "react";
import { Link } from "wouter";
import { AT_ICON_64 } from "@/lib/logos";
import { Button } from "@/components/ui/button";
import { getLoginUrl } from "@/const";
import {
  Shield, Lock, Server, Eye, Key, Database, Cpu, Globe,
  CheckCircle2, ChevronDown, ChevronUp, ArrowRight, HardDrive,
  FileCode, Users, AlertCircle, Zap, Menu, X,
} from "lucide-react";

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-white/5 last:border-0">
      <button onClick={() => setOpen(!open)} className="w-full flex items-center justify-between py-5 text-left gap-4 group">
        <span className="text-sm sm:text-base font-medium text-white/80 group-hover:text-white transition-colors">{question}</span>
        {open ? <ChevronUp className="h-4 w-4 text-white/40 shrink-0" /> : <ChevronDown className="h-4 w-4 text-white/40 shrink-0" />}
      </button>
      {open && <div className="pb-5"><p className="text-sm text-white/50 leading-relaxed">{answer}</p></div>}
    </div>
  );
}

export default function SecurityPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  const pillars = [
    {
      icon: HardDrive,
      title: "Local-first architecture",
      color: "text-blue-400",
      bg: "bg-blue-500/10",
      border: "border-blue-500/20",
      desc: "Titan runs on your machine. Your prompts, credentials, and outputs are processed locally by default. Nothing is sent to external servers unless you explicitly choose to deploy or export.",
      points: ["All AI inference runs in your local environment", "No telemetry or usage data sent to Archibald Titan servers", "Outputs stay on disk until you export or deploy them", "Works fully offline once set up"],
    },
    {
      icon: Lock,
      title: "AES-256 encrypted vault",
      color: "text-emerald-400",
      bg: "bg-emerald-500/10",
      border: "border-emerald-500/20",
      desc: "Every credential stored in Titan is encrypted at rest using AES-256-GCM with a key derived from your master password via PBKDF2. Your master password never leaves your device.",
      points: ["AES-256-GCM encryption at rest", "PBKDF2 key derivation — master password never transmitted", "Zero-knowledge design: Archibald Titan cannot read your vault", "Vault locked automatically on inactivity"],
    },
    {
      icon: Cpu,
      title: "Sandboxed execution",
      color: "text-purple-400",
      bg: "bg-purple-500/10",
      border: "border-purple-500/20",
      desc: "Code generated by Titan Builder runs in an isolated sandbox environment. Scripts cannot access your host filesystem, network, or system resources unless you explicitly grant permission.",
      points: ["Isolated execution environment for all generated code", "No host filesystem access by default", "Network calls blocked unless explicitly enabled", "Sandbox destroyed after each run — no state persistence"],
    },
    {
      icon: Eye,
      title: "Audit trail",
      color: "text-amber-400",
      bg: "bg-amber-500/10",
      border: "border-amber-500/20",
      desc: "Every action in Titan is logged to a tamper-evident local audit trail. Enterprise plans include structured logs exportable to SIEM tools.",
      points: ["Full action log: who did what, when, from which IP", "Tamper-evident log format", "SIEM export (Enterprise+)", "Retention policy configurable per deployment"],
    },
    {
      icon: Key,
      title: "Model and provider controls",
      color: "text-cyan-400",
      bg: "bg-cyan-500/10",
      border: "border-cyan-500/20",
      desc: "You choose which AI models and providers Titan uses. You can restrict to local-only models, block specific providers, or require approval before any external API call is made.",
      points: ["Choose your own model provider (local, OpenAI, Anthropic, etc.)", "Block external providers entirely for air-gapped deployments", "Per-user provider restrictions on team plans", "API key rotation and expiry controls"],
    },
    {
      icon: Users,
      title: "Team governance",
      color: "text-rose-400",
      bg: "bg-rose-500/10",
      border: "border-rose-500/20",
      desc: "Enterprise plans include role-based access control, shared credential vaults with permission scoping, and centralized policy enforcement across your team.",
      points: ["Role-based access control (RBAC)", "Shared vault with per-secret permission scoping", "Admin policy enforcement — restrict features by role", "SSO / SAML integration for enterprise identity providers"],
    },
  ];

  const certifications = [
    { label: "AES-256-GCM", desc: "Vault encryption standard" },
    { label: "PBKDF2", desc: "Key derivation function" },
    { label: "TLS 1.3", desc: "All network transport" },
    { label: "Zero-knowledge", desc: "Vault design" },
    { label: "Local-first", desc: "Default data residency" },
    { label: "RBAC", desc: "Enterprise access control" },
    { label: "SIEM export", desc: "Enterprise audit logs" },
    { label: "Air-gap ready", desc: "Offline deployment" },
  ];

  return (
    <div className="min-h-screen bg-[#060611] text-white overflow-x-hidden">
      {/* NAV */}
      <nav aria-label="Navigation" className="fixed top-0 left-0 right-0 z-50 border-b border-white/5 bg-[#060611]/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
              <img loading="eager" src={AT_ICON_64} alt="AT" className="h-9 w-9 object-contain" />
              <span className="text-lg font-bold tracking-tight">Archibald Titan</span>
            </Link>
            <div className="hidden md:flex items-center gap-6">
              <Link href="/builder" className="text-sm text-white/60 hover:text-white transition-colors">Builder</Link>
              <Link href="/use-cases" className="text-sm text-white/60 hover:text-white transition-colors">Use Cases</Link>
              <span className="text-sm text-blue-400 font-semibold">Security</span>
              <Link href="/pricing" className="text-sm text-white/60 hover:text-white transition-colors">Pricing</Link>
            </div>
            <div className="flex items-center gap-2">
              <Button onClick={() => { window.location.href = getLoginUrl(); }} size="sm" variant="ghost" className="text-white/70 hover:text-white hidden sm:flex">Sign In</Button>
              <Button onClick={() => { window.location.href = getLoginUrl(); }} size="sm" className="bg-blue-600 hover:bg-blue-500 text-white border-0">Get Started</Button>
              <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="md:hidden flex items-center justify-center h-9 w-9 rounded-lg border border-white/10 bg-white/5 text-white" aria-label="Toggle menu">
                {mobileMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
              </button>
            </div>
          </div>
        </div>
        {mobileMenuOpen && (
          <div className="md:hidden border-t border-white/5 bg-[#060611]/95 backdrop-blur-xl">
            <div className="max-w-7xl mx-auto px-4 py-4 flex flex-col gap-1">
              <Link href="/builder" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Builder</Link>
              <Link href="/use-cases" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Use Cases</Link>
              <Link href="/pricing" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Pricing</Link>
            </div>
          </div>
        )}
      </nav>

      {/* HERO */}
      <section className="relative pt-32 pb-20 sm:pt-40 sm:pb-28">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[500px] bg-emerald-600/8 rounded-full blur-[130px]" />
          <div className="absolute bottom-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-emerald-500/20 to-transparent" />
        </div>
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-emerald-500/20 bg-emerald-500/5 mb-8">
            <Shield className="h-3.5 w-3.5 text-emerald-400" />
            <span className="text-xs font-medium text-emerald-300">Security & Privacy Architecture</span>
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.05]">
            <span className="text-white">Built for workflows</span><br />
            <span className="bg-gradient-to-r from-emerald-400 via-teal-400 to-cyan-500 bg-clip-text text-transparent">where data stays yours.</span>
          </h1>
          <p className="mt-6 text-lg sm:text-xl text-white/50 max-w-2xl mx-auto leading-relaxed">
            Titan is designed local-first. Your credentials, prompts, and outputs are processed on your machine by default — not sent to our servers, not stored in the cloud, not shared with anyone.
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-x-8 gap-y-3">
            {[
              { icon: Lock, label: "AES-256 vault" },
              { icon: HardDrive, label: "Local-first" },
              { icon: Cpu, label: "Sandboxed execution" },
              { icon: Eye, label: "Full audit trail" },
            ].map((item) => (
              <div key={item.label} className="flex items-center gap-2 text-sm text-white/40">
                <item.icon className="h-4 w-4 text-emerald-400/60" />{item.label}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SECURITY PILLARS */}
      <section className="relative py-20 sm:py-28">
        <div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <span className="text-sm font-semibold text-emerald-400 tracking-widest uppercase">Architecture</span>
            <h2 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight">Six layers of security</h2>
            <p className="mt-4 text-white/50 max-w-2xl mx-auto">Every layer is designed to keep your data under your control, whether you are a solo developer or an enterprise team.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {pillars.map((p) => (
              <div key={p.title} className={`p-6 rounded-2xl border ${p.border} bg-white/[0.02] hover:bg-white/[0.04] transition-all duration-300`}>
                <div className={`inline-flex p-2.5 rounded-xl ${p.bg} mb-4`}>
                  <p.icon className={`h-5 w-5 ${p.color}`} />
                </div>
                <h3 className="text-base font-semibold text-white mb-2">{p.title}</h3>
                <p className="text-sm text-white/50 leading-relaxed mb-4">{p.desc}</p>
                <ul className="space-y-1.5">
                  {p.points.map((pt) => (
                    <li key={pt} className="flex items-start gap-2 text-xs text-white/40">
                      <CheckCircle2 className={`h-3.5 w-3.5 ${p.color} shrink-0 mt-0.5`} />{pt}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* DATA FLOW DIAGRAM (text-based) */}
      <section className="relative py-20 sm:py-24 bg-white/[0.01]">
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="text-sm font-semibold text-emerald-400 tracking-widest uppercase">Data Flow</span>
            <h2 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight">Where your data goes</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[
              { step: "01", label: "Your machine", desc: "Prompts written, credentials stored, outputs generated — all locally.", icon: Server, color: "text-blue-400", border: "border-blue-500/20", bg: "bg-blue-500/5" },
              { step: "02", label: "Local AI runtime", desc: "Inference runs in your local environment. No prompt data sent to Archibald Titan.", icon: Cpu, color: "text-purple-400", border: "border-purple-500/20", bg: "bg-purple-500/5" },
              { step: "03", label: "External only if you choose", desc: "Deploy, export, or call external APIs only when you explicitly trigger it.", icon: Globe, color: "text-emerald-400", border: "border-emerald-500/20", bg: "bg-emerald-500/5" },
            ].map((item) => (
              <div key={item.step} className={`p-6 rounded-2xl border ${item.border} ${item.bg}`}>
                <div className="text-xs font-bold text-white/20 mb-3">{item.step}</div>
                <item.icon className={`h-6 w-6 ${item.color} mb-3`} />
                <h3 className="text-sm font-semibold text-white mb-2">{item.label}</h3>
                <p className="text-xs text-white/50 leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
          <div className="mt-8 p-5 rounded-2xl border border-white/5 bg-white/[0.02]">
            <div className="flex items-start gap-3">
              <AlertCircle className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-white/80 mb-1">What we do collect</p>
                <p className="text-sm text-white/40 leading-relaxed">When you use cloud-connected features (e.g. Titan marketplace, team sync, or cloud backup), we collect only what is necessary to deliver that feature. We never sell data. Full details in our <Link href="/privacy" className="text-blue-400 hover:text-blue-300 underline underline-offset-2">Privacy Policy</Link>.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* STANDARDS STRIP */}
      <section className="relative py-16">
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <span className="text-sm font-semibold text-white/40 tracking-widest uppercase">Standards & Protocols</span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {certifications.map((c) => (
              <div key={c.label} className="p-4 rounded-xl border border-white/5 bg-white/[0.02] text-center">
                <div className="text-sm font-bold text-white mb-1">{c.label}</div>
                <div className="text-xs text-white/40">{c.desc}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="relative py-20 sm:py-28">
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="text-sm font-semibold text-emerald-400 tracking-widest uppercase">FAQ</span>
            <h2 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight">Security questions</h2>
          </div>
          <div className="divide-y divide-white/5">
            <FAQItem question="Does Archibald Titan have access to my vault?" answer="No. Your vault is encrypted with a key derived from your master password using PBKDF2. Your master password never leaves your device, and Archibald Titan servers never receive your encryption key. This is a zero-knowledge design — we cannot read your vault even if we wanted to." />
            <FAQItem question="Can I run Titan completely offline?" answer="Yes. Titan is designed to run fully offline once installed. All AI inference, credential management, and build operations run locally. You only need internet access for optional features like marketplace, team sync, or cloud backup." />
            <FAQItem question="What happens to my prompts?" answer="Your prompts are processed locally by the AI runtime on your machine. They are not sent to Archibald Titan servers. If you choose to use a cloud AI provider (e.g. OpenAI), your prompts are sent directly to that provider under their terms — not routed through our servers." />
            <FAQItem question="Is the sandbox truly isolated?" answer="Yes. Generated code runs in a sandboxed environment that cannot access your host filesystem, network, or system resources unless you explicitly grant permission. The sandbox is destroyed after each run." />
            <FAQItem question="What encryption does the vault use?" answer="AES-256-GCM for encryption at rest. Keys are derived using PBKDF2 with a high iteration count. The vault is locked automatically after a configurable inactivity period." />
            <FAQItem question="Do you support enterprise compliance requirements?" answer="Enterprise plans include RBAC, SIEM-compatible audit log export, SSO/SAML integration, and on-premise deployment options. Contact us to discuss specific compliance requirements." />
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="relative py-20 sm:py-28">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[300px] bg-emerald-600/8 rounded-full blur-[120px]" />
        </div>
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight">Build with confidence</h2>
          <p className="mt-4 text-white/50 text-lg max-w-xl mx-auto">Titan is designed for teams and individuals who cannot afford to compromise on data security.</p>
          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button size="lg" onClick={() => { window.location.href = getLoginUrl(); }} className="bg-blue-600 hover:bg-blue-500 text-white border-0 shadow-xl shadow-blue-600/25 h-14 px-10 text-base font-semibold gap-3">
              <Zap className="h-5 w-5" /> Get Started Free
            </Button>
            <Link href="/contact">
              <Button size="lg" variant="outline" className="border-white/10 bg-white/5 hover:bg-white/10 text-white h-12 px-8 text-base">
                Talk to Security Team <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="relative border-t border-white/5 py-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <img loading="eager" src={AT_ICON_64} alt="AT" className="h-7 w-7 object-contain" />
            <span className="text-sm font-bold tracking-tight">Archibald Titan</span>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="text-xs text-white/30 hover:text-white/60 transition-colors">Privacy</Link>
            <Link href="/terms" className="text-xs text-white/30 hover:text-white/60 transition-colors">Terms</Link>
            <Link href="/contact" className="text-xs text-white/30 hover:text-white/60 transition-colors">Contact</Link>
          </div>
          <p className="text-xs text-white/20">&copy; {new Date().getFullYear()} Archibald Titan</p>
        </div>
      </footer>
    </div>
  );
}
'''

# ─────────────────────────────────────────────────────────────────────────────
# 2. USE CASES PAGE
# ─────────────────────────────────────────────────────────────────────────────
use_cases_page = '''import { useState } from "react";
import { Link } from "wouter";
import { AT_ICON_64 } from "@/lib/logos";
import { Button } from "@/components/ui/button";
import { getLoginUrl } from "@/const";
import {
  Rocket, Code2, Users, Building2, FileCode, LayoutDashboard,
  Globe, Zap, ArrowRight, CheckCircle2, ChevronDown, ChevronUp,
  Layers, BookOpen, Target, Menu, X, Star,
} from "lucide-react";

const USE_CASES = [
  {
    id: "founders",
    icon: Rocket,
    audience: "Founders & Solo Builders",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    border: "border-blue-500/20",
    tagline: "Go from idea to working product without a full team.",
    desc: "Titan Builder lets you move from concept to launch-ready output in hours, not weeks. Generate landing pages, business plans, MVPs, and pitch decks — all from plain-language briefs.",
    outputs: [
      "Launch-ready landing page with hero, features, pricing, and CTA",
      "Business plan with market analysis and financial model",
      "MVP prototype with real UI and routing",
      "Investor pitch deck structure and narrative",
      "Go-to-market strategy document",
    ],
    example: {
      brief: "Build me a landing page for a B2B SaaS tool that helps law firms track billable hours",
      output: "Full HTML/CSS landing page — hero, feature grid, social proof, pricing table, FAQ, CTA. Responsive, dark mode, ready to deploy.",
    },
  },
  {
    id: "developers",
    icon: Code2,
    audience: "Developers",
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    border: "border-purple-500/20",
    tagline: "Accelerate development without giving up technical control.",
    desc: "Generate boilerplate, scaffold projects, write automation scripts, and prototype integrations — all in a sandboxed environment where you review and own every line of output.",
    outputs: [
      "TypeScript/Python project scaffolds with full structure",
      "REST API boilerplate with auth, routing, and DB schema",
      "Automation scripts for data processing and API integrations",
      "Database migration files and seed scripts",
      "Docker and CI/CD configuration files",
    ],
    example: {
      brief: "Scaffold a Node.js REST API with JWT auth, PostgreSQL, and rate limiting",
      output: "Full project structure: routes, middleware, models, migrations, .env template, README, and Dockerfile.",
    },
  },
  {
    id: "agencies",
    icon: Users,
    audience: "Agencies & Freelancers",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    border: "border-emerald-500/20",
    tagline: "Deliver client work faster with higher margins.",
    desc: "Clone, adapt, and ship web assets and internal tools with better turnaround. Use Titan Builder to produce first drafts, iterate with clients, and export production-ready outputs.",
    outputs: [
      "Client landing pages and marketing sites",
      "Internal tools and admin dashboards",
      "Brand voice documents and content guidelines",
      "Proposal and SOW templates",
      "SEO content briefs and article outlines",
    ],
    example: {
      brief: "Build an internal tool for a restaurant chain to manage shift scheduling across 12 locations",
      output: "Admin dashboard with location selector, shift calendar, staff roster, and export to CSV. React + Tailwind, fully editable.",
    },
  },
  {
    id: "enterprise",
    icon: Building2,
    audience: "Enterprise & Security-Sensitive Teams",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    border: "border-amber-500/20",
    tagline: "Use AI without exposing sensitive workflows to the cloud.",
    desc: "Titan's local-first architecture means your prompts, credentials, and outputs never leave your environment unless you choose. Enterprise plans add RBAC, audit logs, and SSO.",
    outputs: [
      "Internal policy and procedure documents",
      "Compliance checklists and audit templates",
      "Data processing agreements and privacy notices",
      "Internal tooling with RBAC and audit trail",
      "Secure credential management workflows",
    ],
    example: {
      brief: "Generate a GDPR data processing agreement template for a healthcare SaaS company",
      output: "Full DPA document with all required GDPR clauses, controller/processor definitions, data categories, retention schedules, and sub-processor list.",
    },
  },
  {
    id: "internal-tools",
    icon: LayoutDashboard,
    audience: "Operations & Internal Tools",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    border: "border-cyan-500/20",
    tagline: "Build the tools your team actually needs.",
    desc: "Stop waiting for engineering bandwidth. Titan Builder produces functional internal tools — dashboards, CRUD interfaces, reporting views, and operational panels — that your team can use immediately.",
    outputs: [
      "Operations dashboards with real data structures",
      "CRUD admin panels for internal databases",
      "Reporting views and data export tools",
      "Onboarding checklists and workflow trackers",
      "Internal knowledge base templates",
    ],
    example: {
      brief: "Build a dashboard for tracking customer support ticket volume and resolution time by agent",
      output: "React dashboard with date range picker, agent performance table, ticket volume chart, and CSV export. Connects to your existing data source.",
    },
  },
  {
    id: "content",
    icon: BookOpen,
    audience: "Content & Documentation",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    border: "border-rose-500/20",
    tagline: "Produce structured, professional documents at scale.",
    desc: "From product documentation to business plans, Titan Builder produces structured, editable documents that follow professional formats — not just raw text dumps.",
    outputs: [
      "Product requirements documents (PRDs)",
      "Technical architecture documents",
      "User documentation and help centre articles",
      "Business plans with financial models",
      "Grant applications and funding proposals",
    ],
    example: {
      brief: "Write a PRD for a mobile app that helps users track their daily water intake",
      output: "Full PRD: problem statement, user personas, functional requirements, non-functional requirements, user stories, acceptance criteria, and success metrics.",
    },
  },
];

export default function UseCasesPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [activeCase, setActiveCase] = useState("founders");
  const active = USE_CASES.find(u => u.id === activeCase) || USE_CASES[0];
  const Icon = active.icon;

  return (
    <div className="min-h-screen bg-[#060611] text-white overflow-x-hidden">
      {/* NAV */}
      <nav aria-label="Navigation" className="fixed top-0 left-0 right-0 z-50 border-b border-white/5 bg-[#060611]/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
              <img loading="eager" src={AT_ICON_64} alt="AT" className="h-9 w-9 object-contain" />
              <span className="text-lg font-bold tracking-tight">Archibald Titan</span>
            </Link>
            <div className="hidden md:flex items-center gap-6">
              <Link href="/builder" className="text-sm text-white/60 hover:text-white transition-colors">Builder</Link>
              <span className="text-sm text-blue-400 font-semibold">Use Cases</span>
              <Link href="/examples" className="text-sm text-white/60 hover:text-white transition-colors">Examples</Link>
              <Link href="/security" className="text-sm text-white/60 hover:text-white transition-colors">Security</Link>
              <Link href="/pricing" className="text-sm text-white/60 hover:text-white transition-colors">Pricing</Link>
            </div>
            <div className="flex items-center gap-2">
              <Button onClick={() => { window.location.href = getLoginUrl(); }} size="sm" variant="ghost" className="text-white/70 hover:text-white hidden sm:flex">Sign In</Button>
              <Button onClick={() => { window.location.href = getLoginUrl(); }} size="sm" className="bg-blue-600 hover:bg-blue-500 text-white border-0">Get Started</Button>
              <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="md:hidden flex items-center justify-center h-9 w-9 rounded-lg border border-white/10 bg-white/5 text-white" aria-label="Toggle menu">
                {mobileMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
              </button>
            </div>
          </div>
        </div>
        {mobileMenuOpen && (
          <div className="md:hidden border-t border-white/5 bg-[#060611]/95 backdrop-blur-xl">
            <div className="max-w-7xl mx-auto px-4 py-4 flex flex-col gap-1">
              <Link href="/builder" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Builder</Link>
              <Link href="/examples" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Examples</Link>
              <Link href="/security" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Security</Link>
              <Link href="/pricing" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Pricing</Link>
            </div>
          </div>
        )}
      </nav>

      {/* HERO */}
      <section className="relative pt-32 pb-16 sm:pt-40 sm:pb-24">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[500px] bg-blue-600/8 rounded-full blur-[130px]" />
        </div>
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-blue-500/20 bg-blue-500/5 mb-8">
            <Target className="h-3.5 w-3.5 text-blue-400" />
            <span className="text-xs font-medium text-blue-300">Use Cases</span>
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.05]">
            <span className="text-white">What people build</span><br />
            <span className="bg-gradient-to-r from-blue-400 via-blue-500 to-indigo-500 bg-clip-text text-transparent">with Titan Builder.</span>
          </h1>
          <p className="mt-6 text-lg sm:text-xl text-white/50 max-w-2xl mx-auto leading-relaxed">
            From solo founders shipping their first product to enterprise teams building internal tools — here is how different people use Titan Builder to get real work done.
          </p>
        </div>
      </section>

      {/* INTERACTIVE USE CASE EXPLORER */}
      <section className="relative py-16 sm:py-24">
        <div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Selector */}
            <div className="lg:col-span-1 space-y-2">
              {USE_CASES.map((uc) => {
                const UCIcon = uc.icon;
                const isActive = activeCase === uc.id;
                return (
                  <button
                    key={uc.id}
                    onClick={() => setActiveCase(uc.id)}
                    className={`w-full flex items-center gap-3 p-4 rounded-xl border text-left transition-all duration-200 ${isActive ? `${uc.border} ${uc.bg}` : "border-white/5 bg-white/[0.02] hover:bg-white/[0.04]"}`}
                  >
                    <UCIcon className={`h-5 w-5 shrink-0 ${isActive ? uc.color : "text-white/30"}`} />
                    <div>
                      <div className={`text-sm font-semibold ${isActive ? "text-white" : "text-white/60"}`}>{uc.audience}</div>
                      {isActive && <div className="text-xs text-white/40 mt-0.5">{uc.tagline}</div>}
                    </div>
                  </button>
                );
              })}
            </div>
            {/* Detail */}
            <div className="lg:col-span-2 space-y-5">
              <div className={`p-6 rounded-2xl border ${active.border} ${active.bg}`}>
                <div className="flex items-center gap-3 mb-4">
                  <div className={`p-2.5 rounded-xl bg-white/5`}>
                    <Icon className={`h-6 w-6 ${active.color}`} />
                  </div>
                  <div>
                    <h2 className="text-lg font-bold text-white">{active.audience}</h2>
                    <p className={`text-sm ${active.color}`}>{active.tagline}</p>
                  </div>
                </div>
                <p className="text-sm text-white/60 leading-relaxed mb-5">{active.desc}</p>
                <div className="space-y-2">
                  <p className="text-xs font-semibold text-white/40 uppercase tracking-wider mb-3">What you can produce</p>
                  {active.outputs.map((o) => (
                    <div key={o} className="flex items-start gap-2 text-sm text-white/70">
                      <CheckCircle2 className={`h-4 w-4 ${active.color} shrink-0 mt-0.5`} />{o}
                    </div>
                  ))}
                </div>
              </div>
              <div className="p-6 rounded-2xl border border-white/5 bg-white/[0.02]">
                <p className="text-xs font-semibold text-white/40 uppercase tracking-wider mb-4">Example</p>
                <div className="space-y-3">
                  <div>
                    <p className="text-xs text-white/30 mb-1">Brief</p>
                    <p className="text-sm text-white/70 italic leading-relaxed">&ldquo;{active.example.brief}&rdquo;</p>
                  </div>
                  <div className="h-px bg-white/5" />
                  <div>
                    <p className="text-xs text-white/30 mb-1">Output</p>
                    <p className="text-sm text-white/70 leading-relaxed">{active.example.output}</p>
                  </div>
                </div>
              </div>
              <div className="flex gap-3">
                <Link href="/builder">
                  <Button className="bg-blue-600 hover:bg-blue-500 text-white border-0 gap-2">
                    <Zap className="h-4 w-4" /> Try Titan Builder
                  </Button>
                </Link>
                <Link href="/examples">
                  <Button variant="outline" className="border-white/10 bg-white/5 hover:bg-white/10 text-white gap-2">
                    See More Examples <ArrowRight className="h-4 w-4" />
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="relative border-t border-white/5 py-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <img loading="eager" src={AT_ICON_64} alt="AT" className="h-7 w-7 object-contain" />
            <span className="text-sm font-bold tracking-tight">Archibald Titan</span>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="text-xs text-white/30 hover:text-white/60 transition-colors">Privacy</Link>
            <Link href="/terms" className="text-xs text-white/30 hover:text-white/60 transition-colors">Terms</Link>
            <Link href="/contact" className="text-xs text-white/30 hover:text-white/60 transition-colors">Contact</Link>
          </div>
          <p className="text-xs text-white/20">&copy; {new Date().getFullYear()} Archibald Titan</p>
        </div>
      </footer>
    </div>
  );
}
'''

# ─────────────────────────────────────────────────────────────────────────────
# 3. EXAMPLES PAGE
# ─────────────────────────────────────────────────────────────────────────────
examples_page = '''import { useState } from "react";
import { Link } from "wouter";
import { AT_ICON_64 } from "@/lib/logos";
import { Button } from "@/components/ui/button";
import { getLoginUrl } from "@/const";
import {
  Rocket, Code2, FileCode, LayoutDashboard, Settings, BookOpen,
  Globe, Zap, ArrowRight, Copy, CheckCircle2, Menu, X, Layers,
} from "lucide-react";

type Tag = "All" | "Web" | "App" | "Tool" | "Doc" | "Code";

const EXAMPLES = [
  {
    id: 1, tag: "Web" as Tag,
    title: "SaaS Landing Page",
    audience: "Founders",
    icon: Rocket,
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    brief: "Build a landing page for a project management SaaS targeting remote teams",
    output: "Full HTML/CSS page — hero with animated headline, 6-feature grid, social proof strip, 3-tier pricing table, FAQ accordion, and CTA section. Responsive, dark mode, deploy-ready.",
    lines: "~480 lines",
    time: "~45 sec",
  },
  {
    id: 2, tag: "App" as Tag,
    title: "MVP Prototype",
    audience: "Developers",
    icon: Layers,
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
    brief: "Scaffold a React MVP for a habit tracking app with streaks and reminders",
    output: "React + TypeScript project: 8 components, routing, local state, habit CRUD, streak calculator, reminder logic, and a clean mobile-first UI.",
    lines: "~620 lines",
    time: "~60 sec",
  },
  {
    id: 3, tag: "Tool" as Tag,
    title: "Admin Dashboard",
    audience: "Operations teams",
    icon: LayoutDashboard,
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
    brief: "Build an admin dashboard for monitoring customer support tickets by agent and priority",
    output: "React dashboard: date range filter, agent performance table with sortable columns, ticket volume bar chart, priority breakdown pie chart, and CSV export.",
    lines: "~390 lines",
    time: "~50 sec",
  },
  {
    id: 4, tag: "Doc" as Tag,
    title: "Business Plan",
    audience: "Founders",
    icon: FileCode,
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
    brief: "Write a business plan for a B2B SaaS selling compliance software to law firms",
    output: "12-section document: executive summary, problem/solution, market sizing, competitive analysis, product overview, go-to-market strategy, team, financials (3-year model), risks, and appendix.",
    lines: "~2,800 words",
    time: "~90 sec",
  },
  {
    id: 5, tag: "Code" as Tag,
    title: "Automation Script",
    audience: "Developers",
    icon: Settings,
    color: "text-amber-400",
    bg: "bg-amber-500/10",
    brief: "Write a Python script that pulls data from a Shopify store and syncs it to a Google Sheet",
    output: "Python script with Shopify API client, Google Sheets API integration, incremental sync logic, error handling, retry logic, and .env config template.",
    lines: "~280 lines",
    time: "~35 sec",
  },
  {
    id: 6, tag: "Doc" as Tag,
    title: "Product Requirements Doc",
    audience: "Product teams",
    icon: BookOpen,
    color: "text-rose-400",
    bg: "bg-rose-500/10",
    brief: "Write a PRD for a mobile app that helps users track daily water intake",
    output: "Full PRD: problem statement, user personas, functional requirements, non-functional requirements, user stories with acceptance criteria, success metrics, and out-of-scope items.",
    lines: "~1,900 words",
    time: "~75 sec",
  },
  {
    id: 7, tag: "Web" as Tag,
    title: "Agency Portfolio Site",
    audience: "Agencies",
    icon: Globe,
    color: "text-purple-400",
    bg: "bg-purple-500/10",
    brief: "Build a portfolio site for a digital agency specialising in e-commerce brands",
    output: "Multi-section site: animated hero, services grid, case study cards with hover states, team section, client logo strip, testimonials, and contact form. Responsive, accessible.",
    lines: "~520 lines",
    time: "~55 sec",
  },
  {
    id: 8, tag: "Code" as Tag,
    title: "REST API Scaffold",
    audience: "Developers",
    icon: Code2,
    color: "text-teal-400",
    bg: "bg-teal-500/10",
    brief: "Scaffold a Node.js REST API with JWT auth, PostgreSQL, and rate limiting",
    output: "Full project: Express routes, JWT middleware, PostgreSQL models with Drizzle ORM, migrations, rate limiter, error handler, .env template, Dockerfile, and README.",
    lines: "~740 lines",
    time: "~70 sec",
  },
  {
    id: 9, tag: "Tool" as Tag,
    title: "Internal Shift Scheduler",
    audience: "Operations teams",
    icon: LayoutDashboard,
    color: "text-orange-400",
    bg: "bg-orange-500/10",
    brief: "Build an internal tool for a restaurant chain to manage shift scheduling across 12 locations",
    output: "React admin panel: location selector, weekly shift calendar, staff roster with drag-to-assign, conflict detection, and export to CSV/PDF.",
    lines: "~560 lines",
    time: "~65 sec",
  },
  {
    id: 10, tag: "Doc" as Tag,
    title: "GDPR Data Processing Agreement",
    audience: "Legal / Enterprise",
    icon: FileCode,
    color: "text-slate-400",
    bg: "bg-slate-500/10",
    brief: "Generate a GDPR DPA template for a healthcare SaaS company",
    output: "Full DPA: controller/processor definitions, data categories, processing purposes, retention schedules, sub-processor list, security measures, and breach notification clauses.",
    lines: "~3,200 words",
    time: "~95 sec",
  },
  {
    id: 11, tag: "App" as Tag,
    title: "E-commerce Checkout Flow",
    audience: "Developers",
    icon: Layers,
    color: "text-pink-400",
    bg: "bg-pink-500/10",
    brief: "Build a multi-step checkout flow for a Shopify-style e-commerce store",
    output: "React checkout: cart summary, address form with validation, shipping selector, payment form (Stripe-ready), order confirmation, and mobile-optimised layout.",
    lines: "~430 lines",
    time: "~50 sec",
  },
  {
    id: 12, tag: "Web" as Tag,
    title: "Startup Pitch Deck Page",
    audience: "Founders",
    icon: Rocket,
    color: "text-blue-400",
    bg: "bg-blue-500/10",
    brief: "Build a web-based pitch deck for a fintech startup targeting SME lending",
    output: "12-slide web deck: problem, solution, market size, product demo section, business model, traction, team, financials, and ask. Animated slide transitions, investor-ready design.",
    lines: "~510 lines",
    time: "~60 sec",
  },
];

const TAGS: Tag[] = ["All", "Web", "App", "Tool", "Doc", "Code"];

export default function ExamplesPage() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [activeTag, setActiveTag] = useState<Tag>("All");
  const filtered = activeTag === "All" ? EXAMPLES : EXAMPLES.filter(e => e.tag === activeTag);

  return (
    <div className="min-h-screen bg-[#060611] text-white overflow-x-hidden">
      {/* NAV */}
      <nav aria-label="Navigation" className="fixed top-0 left-0 right-0 z-50 border-b border-white/5 bg-[#060611]/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
              <img loading="eager" src={AT_ICON_64} alt="AT" className="h-9 w-9 object-contain" />
              <span className="text-lg font-bold tracking-tight">Archibald Titan</span>
            </Link>
            <div className="hidden md:flex items-center gap-6">
              <Link href="/builder" className="text-sm text-white/60 hover:text-white transition-colors">Builder</Link>
              <Link href="/use-cases" className="text-sm text-white/60 hover:text-white transition-colors">Use Cases</Link>
              <span className="text-sm text-blue-400 font-semibold">Examples</span>
              <Link href="/pricing" className="text-sm text-white/60 hover:text-white transition-colors">Pricing</Link>
            </div>
            <div className="flex items-center gap-2">
              <Button onClick={() => { window.location.href = getLoginUrl(); }} size="sm" variant="ghost" className="text-white/70 hover:text-white hidden sm:flex">Sign In</Button>
              <Button onClick={() => { window.location.href = getLoginUrl(); }} size="sm" className="bg-blue-600 hover:bg-blue-500 text-white border-0">Try Builder</Button>
              <button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="md:hidden flex items-center justify-center h-9 w-9 rounded-lg border border-white/10 bg-white/5 text-white" aria-label="Toggle menu">
                {mobileMenuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
              </button>
            </div>
          </div>
        </div>
        {mobileMenuOpen && (
          <div className="md:hidden border-t border-white/5 bg-[#060611]/95 backdrop-blur-xl">
            <div className="max-w-7xl mx-auto px-4 py-4 flex flex-col gap-1">
              <Link href="/builder" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Builder</Link>
              <Link href="/use-cases" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Use Cases</Link>
              <Link href="/pricing" onClick={() => setMobileMenuOpen(false)} className="block py-2.5 px-3 rounded-lg text-sm text-white/70 hover:text-white hover:bg-white/5">Pricing</Link>
            </div>
          </div>
        )}
      </nav>

      {/* HERO */}
      <section className="relative pt-32 pb-16 sm:pt-40 sm:pb-20">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[400px] bg-blue-600/8 rounded-full blur-[130px]" />
        </div>
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-blue-500/20 bg-blue-500/5 mb-8">
            <Zap className="h-3.5 w-3.5 text-blue-400" />
            <span className="text-xs font-medium text-blue-300">12 real output examples</span>
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.05]">
            <span className="text-white">Real outputs.</span><br />
            <span className="bg-gradient-to-r from-blue-400 via-blue-500 to-indigo-500 bg-clip-text text-transparent">Real briefs.</span>
          </h1>
          <p className="mt-6 text-lg sm:text-xl text-white/50 max-w-2xl mx-auto leading-relaxed">
            Every example below was generated by Titan Builder from a plain-language brief. No templates, no manual editing — just describe what you need and build it.
          </p>
        </div>
      </section>

      {/* FILTER + GRID */}
      <section className="relative py-8 sm:py-12">
        <div className="relative max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Filter tabs */}
          <div className="flex flex-wrap gap-2 mb-10">
            {TAGS.map((tag) => (
              <button
                key={tag}
                onClick={() => setActiveTag(tag)}
                className={`px-4 py-1.5 rounded-full text-sm font-medium transition-all ${activeTag === tag ? "bg-blue-600 text-white" : "bg-white/5 text-white/50 hover:bg-white/10 hover:text-white"}`}
              >
                {tag}
              </button>
            ))}
          </div>
          {/* Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {filtered.map((ex) => {
              const Icon = ex.icon;
              return (
                <div key={ex.id} className="group p-5 rounded-2xl border border-white/[0.06] bg-white/[0.02] hover:bg-white/[0.04] hover:border-white/10 transition-all duration-300">
                  <div className="flex items-start justify-between mb-4">
                    <div className={`p-2 rounded-lg ${ex.bg}`}>
                      <Icon className={`h-4 w-4 ${ex.color}`} />
                    </div>
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-white/5 text-white/40 border border-white/10">{ex.tag}</span>
                  </div>
                  <h3 className="text-sm font-semibold text-white mb-1">{ex.title}</h3>
                  <p className="text-xs text-white/40 mb-4">{ex.audience}</p>
                  <div className="space-y-3 mb-4">
                    <div>
                      <p className="text-[10px] text-white/25 uppercase tracking-wider mb-1">Brief</p>
                      <p className="text-xs text-white/50 italic leading-relaxed">&ldquo;{ex.brief}&rdquo;</p>
                    </div>
                    <div className="h-px bg-white/5" />
                    <div>
                      <p className="text-[10px] text-white/25 uppercase tracking-wider mb-1">Output</p>
                      <p className="text-xs text-white/60 leading-relaxed">{ex.output}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3 pt-3 border-t border-white/5">
                    <span className="text-[10px] text-white/30">{ex.lines}</span>
                    <span className="text-white/20">·</span>
                    <span className="text-[10px] text-white/30">{ex.time} to generate</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="relative py-20 sm:py-28">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[300px] bg-blue-600/8 rounded-full blur-[120px]" />
        </div>
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight">Build your first output</h2>
          <p className="mt-4 text-white/50 text-lg max-w-xl mx-auto">Describe what you need. Titan Builder produces a structured, editable, exportable result.</p>
          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link href="/builder">
              <Button size="lg" className="bg-blue-600 hover:bg-blue-500 text-white border-0 shadow-xl shadow-blue-600/25 h-14 px-10 text-base font-semibold gap-3">
                <Zap className="h-5 w-5" /> Open Titan Builder
              </Button>
            </Link>
            <Link href="/use-cases">
              <Button size="lg" variant="outline" className="border-white/10 bg-white/5 hover:bg-white/10 text-white h-12 px-8 text-base">
                Browse Use Cases <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="relative border-t border-white/5 py-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <img loading="eager" src={AT_ICON_64} alt="AT" className="h-7 w-7 object-contain" />
            <span className="text-sm font-bold tracking-tight">Archibald Titan</span>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="text-xs text-white/30 hover:text-white/60 transition-colors">Privacy</Link>
            <Link href="/terms" className="text-xs text-white/30 hover:text-white/60 transition-colors">Terms</Link>
            <Link href="/contact" className="text-xs text-white/30 hover:text-white/60 transition-colors">Contact</Link>
          </div>
          <p className="text-xs text-white/20">&copy; {new Date().getFullYear()} Archibald Titan</p>
        </div>
      </footer>
    </div>
  );
}
'''

# ─────────────────────────────────────────────────────────────────────────────
# 4. ABOUT PAGE
# ─────────────────────────────────────────────────────────────────────────────
about_page = '''import { Link } from "wouter";
import { AT_ICON_64, FULL_LOGO_256 } from "@/lib/logos";
import { Button } from "@/components/ui/button";
import { getLoginUrl } from "@/const";
import {
  Shield, Zap, Globe, Users, ArrowRight, CheckCircle2,
  Mail, Github, Twitter, Lock, HardDrive, Cpu,
} from "lucide-react";

export default function AboutPage() {
  const values = [
    { icon: HardDrive, title: "Local-first", desc: "Your data stays on your machine by default. We build for privacy, not convenience.", color: "text-blue-400", bg: "bg-blue-500/10" },
    { icon: Shield, title: "Security without compromise", desc: "AES-256 encryption, sandboxed execution, and zero-knowledge vault design.", color: "text-emerald-400", bg: "bg-emerald-500/10" },
    { icon: Zap, title: "Outcomes over features", desc: "We measure success by what users ship, not by how many features we add.", color: "text-amber-400", bg: "bg-amber-500/10" },
    { icon: Globe, title: "Built for real work", desc: "Every feature is designed to produce something useful — not just impressive demos.", color: "text-purple-400", bg: "bg-purple-500/10" },
  ];

  const milestones = [
    { year: "2023", event: "Archibald Titan founded — initial focus on secure credential management for developers." },
    { year: "Q1 2024", event: "Titan Builder launched in private beta — AI-powered build environment for founders and developers." },
    { year: "Q2 2024", event: "Marketplace launched — community-built tools and integrations." },
    { year: "Q3 2024", event: "Enterprise tier launched — RBAC, audit logs, SSO, and on-premise deployment." },
    { year: "Q4 2024", event: "2,400+ active users. 50,000+ builds completed. 15+ integrations." },
    { year: "2025", event: "Titan cyber tools, AI content studio, and advertising automation added to platform." },
  ];

  return (
    <div className="min-h-screen bg-[#060611] text-white overflow-x-hidden">
      {/* NAV */}
      <nav aria-label="Navigation" className="fixed top-0 left-0 right-0 z-50 border-b border-white/5 bg-[#060611]/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
              <img loading="eager" src={AT_ICON_64} alt="AT" className="h-9 w-9 object-contain" />
              <span className="text-lg font-bold tracking-tight">Archibald Titan</span>
            </Link>
            <div className="hidden md:flex items-center gap-6">
              <Link href="/builder" className="text-sm text-white/60 hover:text-white transition-colors">Builder</Link>
              <Link href="/security" className="text-sm text-white/60 hover:text-white transition-colors">Security</Link>
              <Link href="/pricing" className="text-sm text-white/60 hover:text-white transition-colors">Pricing</Link>
              <span className="text-sm text-blue-400 font-semibold">About</span>
            </div>
            <div className="flex items-center gap-2">
              <Button onClick={() => { window.location.href = getLoginUrl(); }} size="sm" variant="ghost" className="text-white/70 hover:text-white hidden sm:flex">Sign In</Button>
              <Button onClick={() => { window.location.href = getLoginUrl(); }} size="sm" className="bg-blue-600 hover:bg-blue-500 text-white border-0">Get Started</Button>
            </div>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section className="relative pt-32 pb-16 sm:pt-40 sm:pb-24">
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[400px] bg-blue-600/8 rounded-full blur-[130px]" />
        </div>
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="flex justify-center mb-8">
            <img src={FULL_LOGO_256} alt="Archibald Titan" className="h-24 w-24 object-contain drop-shadow-[0_0_30px_rgba(59,130,246,0.3)]" />
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black tracking-tight leading-[1.05]">
            <span className="text-white">We build tools for people</span><br />
            <span className="bg-gradient-to-r from-blue-400 via-blue-500 to-indigo-500 bg-clip-text text-transparent">who build things.</span>
          </h1>
          <p className="mt-6 text-lg sm:text-xl text-white/50 max-w-2xl mx-auto leading-relaxed">
            Archibald Titan is a local-first AI platform for founders, developers, and teams who need to build fast without compromising on security or control.
          </p>
        </div>
      </section>

      {/* MISSION */}
      <section className="relative py-16 sm:py-24">
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="p-8 rounded-2xl border border-blue-500/20 bg-blue-500/[0.03]">
            <p className="text-sm font-semibold text-blue-400 uppercase tracking-widest mb-4">Our Mission</p>
            <p className="text-xl sm:text-2xl font-medium text-white leading-relaxed">
              To give every founder, developer, and team access to an AI build environment that is powerful enough to produce real work, and secure enough to trust with sensitive workflows.
            </p>
          </div>
        </div>
      </section>

      {/* VALUES */}
      <section className="relative py-16 sm:py-24">
        <div className="relative max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="text-sm font-semibold text-blue-400 tracking-widest uppercase">What we stand for</span>
            <h2 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight">Our values</h2>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            {values.map((v) => (
              <div key={v.title} className="p-6 rounded-2xl border border-white/5 bg-white/[0.02] hover:bg-white/[0.04] transition-all">
                <div className={`inline-flex p-2.5 rounded-xl ${v.bg} mb-4`}>
                  <v.icon className={`h-5 w-5 ${v.color}`} />
                </div>
                <h3 className="text-base font-semibold text-white mb-2">{v.title}</h3>
                <p className="text-sm text-white/50 leading-relaxed">{v.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* TIMELINE */}
      <section className="relative py-16 sm:py-24 bg-white/[0.01]">
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <span className="text-sm font-semibold text-blue-400 tracking-widest uppercase">History</span>
            <h2 className="mt-3 text-3xl sm:text-4xl font-bold tracking-tight">How we got here</h2>
          </div>
          <div className="space-y-6">
            {milestones.map((m, i) => (
              <div key={i} className="flex gap-5">
                <div className="flex flex-col items-center">
                  <div className="w-2.5 h-2.5 rounded-full bg-blue-500 shrink-0 mt-1.5" />
                  {i < milestones.length - 1 && <div className="w-px flex-1 bg-white/10 mt-2" />}
                </div>
                <div className="pb-6">
                  <p className="text-xs font-bold text-blue-400 mb-1">{m.year}</p>
                  <p className="text-sm text-white/60 leading-relaxed">{m.event}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* STATS */}
      <section className="relative py-16 sm:py-20">
        <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-5">
            {[
              { value: "2,400+", label: "Active users" },
              { value: "50k+", label: "Builds completed" },
              { value: "15+", label: "Integrations" },
              { value: "4.9/5", label: "Average rating" },
            ].map((s) => (
              <div key={s.label} className="p-5 rounded-2xl border border-white/5 bg-white/[0.02] text-center">
                <div className="text-2xl sm:text-3xl font-black text-white mb-1">{s.value}</div>
                <div className="text-xs text-white/40">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CONTACT */}
      <section className="relative py-16 sm:py-24">
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight mb-4">Get in touch</h2>
          <p className="text-white/50 mb-8 max-w-xl mx-auto">Have a question, partnership inquiry, or want to discuss enterprise deployment? We would love to hear from you.</p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link href="/contact">
              <Button size="lg" className="bg-blue-600 hover:bg-blue-500 text-white border-0 h-12 px-8 gap-2">
                <Mail className="h-4 w-4" /> Contact Us
              </Button>
            </Link>
            <Link href="/pricing">
              <Button size="lg" variant="outline" className="border-white/10 bg-white/5 hover:bg-white/10 text-white h-12 px-8 gap-2">
                View Pricing <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="relative border-t border-white/5 py-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <img loading="eager" src={AT_ICON_64} alt="AT" className="h-7 w-7 object-contain" />
            <span className="text-sm font-bold tracking-tight">Archibald Titan</span>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="text-xs text-white/30 hover:text-white/60 transition-colors">Privacy</Link>
            <Link href="/terms" className="text-xs text-white/30 hover:text-white/60 transition-colors">Terms</Link>
            <Link href="/contact" className="text-xs text-white/30 hover:text-white/60 transition-colors">Contact</Link>
          </div>
          <p className="text-xs text-white/20">&copy; {new Date().getFullYear()} Archibald Titan</p>
        </div>
      </footer>
    </div>
  );
}
'''

# ─────────────────────────────────────────────────────────────────────────────
# 5. CHANGELOG PAGE
# ─────────────────────────────────────────────────────────────────────────────
changelog_page = '''import { Link } from "wouter";
import { AT_ICON_64 } from "@/lib/logos";
import { Button } from "@/components/ui/button";
import { getLoginUrl } from "@/const";
import { Zap, Shield, Sparkles, Wrench, ArrowRight, CheckCircle2 } from "lucide-react";

type ChangeType = "feature" | "improvement" | "fix" | "security";

interface Release {
  version: string;
  date: string;
  label?: string;
  changes: { type: ChangeType; text: string }[];
}

const RELEASES: Release[] = [
  {
    version: "v3.8.0",
    date: "March 2025",
    label: "Latest",
    changes: [
      { type: "feature", text: "AI Content Studio — generate platform-optimised content for TikTok, Instagram, LinkedIn, and 12 other platforms" },
      { type: "feature", text: "Message queue in Titan Chat — send messages while Titan is processing without interrupting the current run" },
      { type: "feature", text: "Marketplace payload generator — real, functional code payloads for all marketplace listings" },
      { type: "improvement", text: "Builder page — full Archibald Titan crest logo in hero, tier logos on pricing cards" },
      { type: "improvement", text: "Mobile layout fixes — tab bar scrollable, platform labels no longer truncated on small screens" },
      { type: "security", text: "Builder access gated to paid users — free plan restricted to AI Chat only" },
    ],
  },
  {
    version: "v3.7.0",
    date: "February 2025",
    changes: [
      { type: "feature", text: "Dedicated /builder landing page with 8 sections, examples gallery, and builder-specific FAQ" },
      { type: "feature", text: "Homepage rewrite — new hero, proof strip, audience routing, security section, and updated pricing preview" },
      { type: "feature", text: "Advertising Dashboard — campaign management, ad copy generation, and performance analytics" },
      { type: "improvement", text: "Nav updated with Builder, Use Cases, Security, and Pricing links" },
      { type: "fix", text: "TypeScript compilation errors in marketplace-payload-generator resolved" },
    ],
  },
  {
    version: "v3.6.0",
    date: "January 2025",
    changes: [
      { type: "feature", text: "TikTok Pipeline — automated content scheduling and publishing to TikTok" },
      { type: "feature", text: "SEO Engine — keyword research, SERP analysis, and content brief generation" },
      { type: "feature", text: "Affiliate Dashboard — referral tracking, commission management, and payout reporting" },
      { type: "improvement", text: "Credential health scoring — automated detection of weak, reused, and compromised credentials" },
      { type: "security", text: "Vault lock timeout now configurable per user (1–60 minutes)" },
    ],
  },
  {
    version: "v3.5.0",
    date: "December 2024",
    changes: [
      { type: "feature", text: "Tech Bazaar Marketplace — buy and sell tools, scripts, and integrations built on Titan" },
      { type: "feature", text: "Seller bot system — automated marketplace listings with real functional code payloads" },
      { type: "feature", text: "Crowdfunding module — campaign creation, backer management, and milestone tracking" },
      { type: "improvement", text: "Titan Builder output quality improvements — better structure, more consistent formatting" },
      { type: "fix", text: "Queue indicator now shows dismissible chips per queued message" },
    ],
  },
  {
    version: "v3.4.0",
    date: "November 2024",
    changes: [
      { type: "feature", text: "Argus — autonomous web monitoring and alerting system" },
      { type: "feature", text: "Astra — AI-powered research and intelligence gathering tool" },
      { type: "feature", text: "CyberMCP — Model Context Protocol server for security tooling" },
      { type: "improvement", text: "Dashboard sidebar — Specialised section with cyber tools, research tools, and advanced modules" },
      { type: "security", text: "TOTP vault — time-based one-time password storage with AES-256 encryption" },
    ],
  },
  {
    version: "v3.3.0",
    date: "October 2024",
    changes: [
      { type: "feature", text: "Enterprise tier — RBAC, team vault, SSO/SAML, and full audit trail" },
      { type: "feature", text: "Team management — invite members, assign roles, and manage permissions" },
      { type: "feature", text: "API access — REST API for programmatic credential and builder access" },
      { type: "improvement", text: "Pricing page — task-based economics, usage examples, and upgrade logic" },
      { type: "fix", text: "Credential sync reliability improvements for large vaults (1,000+ credentials)" },
    ],
  },
  {
    version: "v3.2.0",
    date: "September 2024",
    changes: [
      { type: "feature", text: "Titan Builder GA — AI-powered build environment for landing pages, MVPs, tools, and documents" },
      { type: "feature", text: "Sandbox execution — generated code runs in an isolated environment" },
      { type: "feature", text: "Export formats — HTML, CSS, Markdown, JSON, Python, TypeScript, .env, and zip" },
      { type: "improvement", text: "Builder output now includes inline comments and README by default" },
      { type: "security", text: "Sandbox network isolation — generated scripts cannot make external calls without explicit permission" },
    ],
  },
  {
    version: "v3.0.0",
    date: "August 2024",
    changes: [
      { type: "feature", text: "Titan Chat — conversational AI with tool calling, memory, and multi-step reasoning" },
      { type: "feature", text: "Credential fetcher — automated credential retrieval from 15+ provider integrations" },
      { type: "feature", text: "Proxy pool — residential and datacenter proxy management with health monitoring" },
      { type: "improvement", text: "Complete UI redesign — dark-first, accessible, mobile-responsive" },
      { type: "security", text: "AES-256-GCM vault encryption with PBKDF2 key derivation" },
    ],
  },
];

const TYPE_CONFIG: Record<ChangeType, { label: string; color: string; bg: string; border: string; icon: typeof Zap }> = {
  feature:     { label: "New",         color: "text-blue-400",    bg: "bg-blue-500/10",    border: "border-blue-500/20",    icon: Sparkles },
  improvement: { label: "Improved",    color: "text-emerald-400", bg: "bg-emerald-500/10", border: "border-emerald-500/20", icon: Zap },
  fix:         { label: "Fixed",       color: "text-amber-400",   bg: "bg-amber-500/10",   border: "border-amber-500/20",   icon: Wrench },
  security:    { label: "Security",    color: "text-rose-400",    bg: "bg-rose-500/10",    border: "border-rose-500/20",    icon: Shield },
};

export default function ChangelogPage() {
  return (
    <div className="min-h-screen bg-[#060611] text-white overflow-x-hidden">
      {/* NAV */}
      <nav aria-label="Navigation" className="fixed top-0 left-0 right-0 z-50 border-b border-white/5 bg-[#060611]/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
              <img loading="eager" src={AT_ICON_64} alt="AT" className="h-9 w-9 object-contain" />
              <span className="text-lg font-bold tracking-tight">Archibald Titan</span>
            </Link>
            <div className="hidden md:flex items-center gap-6">
              <Link href="/builder" className="text-sm text-white/60 hover:text-white transition-colors">Builder</Link>
              <Link href="/pricing" className="text-sm text-white/60 hover:text-white transition-colors">Pricing</Link>
              <span className="text-sm text-blue-400 font-semibold">Changelog</span>
            </div>
            <div className="flex items-center gap-2">
              <Button onClick={() => { window.location.href = getLoginUrl(); }} size="sm" className="bg-blue-600 hover:bg-blue-500 text-white border-0">Get Started</Button>
            </div>
          </div>
        </div>
      </nav>

      {/* HERO */}
      <section className="relative pt-32 pb-12 sm:pt-40 sm:pb-16">
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full border border-blue-500/20 bg-blue-500/5 mb-8">
            <Zap className="h-3.5 w-3.5 text-blue-400" />
            <span className="text-xs font-medium text-blue-300">Release history</span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-black tracking-tight">Changelog</h1>
          <p className="mt-4 text-white/50 max-w-xl mx-auto">Every release, every improvement, every fix — documented here.</p>
        </div>
      </section>

      {/* RELEASES */}
      <section className="relative py-8 pb-24">
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="space-y-10">
            {RELEASES.map((release) => (
              <div key={release.version} className="relative">
                <div className="flex items-center gap-4 mb-5">
                  <div className="flex items-center gap-3">
                    <span className="text-lg font-black text-white">{release.version}</span>
                    {release.label && (
                      <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-blue-500 text-white">
                        {release.label}
                      </span>
                    )}
                  </div>
                  <span className="text-sm text-white/30">{release.date}</span>
                </div>
                <div className="space-y-2.5 pl-4 border-l border-white/5">
                  {release.changes.map((change, i) => {
                    const cfg = TYPE_CONFIG[change.type];
                    const Icon = cfg.icon;
                    return (
                      <div key={i} className="flex items-start gap-3">
                        <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold ${cfg.bg} ${cfg.color} border ${cfg.border} shrink-0 mt-0.5`}>
                          <Icon className="h-2.5 w-2.5" />{cfg.label}
                        </span>
                        <p className="text-sm text-white/60 leading-relaxed">{change.text}</p>
                      </div>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* FOOTER */}
      <footer className="relative border-t border-white/5 py-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <img loading="eager" src={AT_ICON_64} alt="AT" className="h-7 w-7 object-contain" />
            <span className="text-sm font-bold tracking-tight">Archibald Titan</span>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/privacy" className="text-xs text-white/30 hover:text-white/60 transition-colors">Privacy</Link>
            <Link href="/terms" className="text-xs text-white/30 hover:text-white/60 transition-colors">Terms</Link>
            <Link href="/contact" className="text-xs text-white/30 hover:text-white/60 transition-colors">Contact</Link>
          </div>
          <p className="text-xs text-white/20">&copy; {new Date().getFullYear()} Archibald Titan</p>
        </div>
      </footer>
    </div>
  );
}
'''

pages = {
    "SecurityPage.tsx": security_page,
    "UseCasesPage.tsx": use_cases_page,
    "ExamplesPage.tsx": examples_page,
    "AboutPage.tsx": about_page,
    "ChangelogPage.tsx": changelog_page,
}

for filename, content in pages.items():
    path = os.path.join(BASE, filename)
    with open(path, "w") as f:
        f.write(content)
    print(f"Written: {path} ({len(content.splitlines())} lines)")

print("All 5 pages written successfully.")
