CREATE TABLE `fetcher_proxies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`label` varchar(128) NOT NULL,
	`protocol` enum('http','https','socks5') NOT NULL DEFAULT 'http',
	`host` varchar(256) NOT NULL,
	`port` int NOT NULL,
	`username` varchar(128),
	`password` text,
	`proxyType` enum('residential','datacenter','mobile','isp') NOT NULL DEFAULT 'residential',
	`country` varchar(8),
	`city` varchar(128),
	`healthy` int NOT NULL DEFAULT 1,
	`latencyMs` int,
	`lastCheckedAt` timestamp,
	`lastUsedAt` timestamp,
	`failCount` int NOT NULL DEFAULT 0,
	`successCount` int NOT NULL DEFAULT 0,
	`provider` varchar(128),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `fetcher_proxies_id` PRIMARY KEY(`id`)
);
