CREATE TABLE `replicate_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`sandboxId` int,
	`targetUrl` varchar(2048) NOT NULL,
	`targetName` varchar(256) NOT NULL,
	`targetDescription` text,
	`researchData` json,
	`buildPlan` json,
	`brandName` varchar(256),
	`brandColors` json,
	`brandLogo` text,
	`brandTagline` varchar(512),
	`stripePublishableKey` text,
	`stripeSecretKey` text,
	`stripePriceIds` json,
	`status` enum('researching','research_complete','planning','plan_complete','building','build_complete','testing','complete','error') NOT NULL DEFAULT 'researching',
	`currentStep` int NOT NULL DEFAULT 0,
	`totalSteps` int NOT NULL DEFAULT 0,
	`statusMessage` text,
	`errorMessage` text,
	`buildLog` json,
	`outputFiles` json,
	`previewUrl` text,
	`priority` enum('mvp','full') NOT NULL DEFAULT 'mvp',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `replicate_projects_id` PRIMARY KEY(`id`)
);
