-- Content Creator System — Migration 0041
-- Tables: content_creator_campaigns, content_creator_pieces, content_creator_schedules, content_creator_analytics

CREATE TABLE IF NOT EXISTS `content_creator_campaigns` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `name` varchar(255) NOT NULL,
  `objective` varchar(100) NOT NULL DEFAULT 'brand_awareness',
  `description` text,
  `targetAudience` text,
  `brandVoice` varchar(100) NOT NULL DEFAULT 'confident',
  `primaryKeywords` json,
  `platforms` json NOT NULL,
  `status` enum('draft','active','paused','completed','archived') NOT NULL DEFAULT 'draft',
  `startDate` timestamp NULL,
  `endDate` timestamp NULL,
  `totalPieces` int NOT NULL DEFAULT 0,
  `publishedPieces` int NOT NULL DEFAULT 0,
  `totalImpressions` int NOT NULL DEFAULT 0,
  `totalClicks` int NOT NULL DEFAULT 0,
  `totalEngagements` int NOT NULL DEFAULT 0,
  `seoLinked` boolean NOT NULL DEFAULT false,
  `advertisingLinked` boolean NOT NULL DEFAULT false,
  `tiktokLinked` boolean NOT NULL DEFAULT false,
  `aiStrategy` text,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `content_creator_pieces` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `campaignId` int,
  `platform` enum('tiktok','instagram','x_twitter','linkedin','reddit','facebook','youtube_shorts','blog','email','pinterest','discord','telegram','whatsapp','medium','hackernews') NOT NULL,
  `contentType` enum('video_script','photo_carousel','social_post','ad_copy','blog_article','email_campaign','story','reel','thread','infographic') NOT NULL,
  `title` varchar(500),
  `body` text NOT NULL,
  `headline` varchar(500),
  `callToAction` varchar(255),
  `hashtags` json,
  `mediaUrl` text,
  `imagePrompt` text,
  `videoScript` text,
  `hook` varchar(500),
  `visualDirections` json,
  `seoKeywords` json,
  `seoScore` int DEFAULT 0,
  `qualityScore` int DEFAULT 0,
  `status` enum('draft','review','approved','scheduled','published','failed','archived') NOT NULL DEFAULT 'draft',
  `scheduledAt` timestamp NULL,
  `publishedAt` timestamp NULL,
  `externalPostId` varchar(255),
  `externalUrl` text,
  `impressions` int NOT NULL DEFAULT 0,
  `clicks` int NOT NULL DEFAULT 0,
  `engagements` int NOT NULL DEFAULT 0,
  `shares` int NOT NULL DEFAULT 0,
  `saves` int NOT NULL DEFAULT 0,
  `comments` int NOT NULL DEFAULT 0,
  `aiPrompt` text,
  `aiModel` varchar(50),
  `generationMs` int,
  `tiktokPublishId` varchar(255),
  `linkedMarketingContentId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `content_creator_schedules` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `pieceId` int NOT NULL,
  `campaignId` int,
  `platform` varchar(50) NOT NULL,
  `scheduledAt` timestamp NOT NULL,
  `status` enum('pending','processing','published','failed','cancelled') NOT NULL DEFAULT 'pending',
  `publishedAt` timestamp NULL,
  `failReason` text,
  `retryCount` int NOT NULL DEFAULT 0,
  `maxRetries` int NOT NULL DEFAULT 3,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `content_creator_analytics` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `pieceId` int NOT NULL,
  `campaignId` int,
  `platform` varchar(50) NOT NULL,
  `date` varchar(10) NOT NULL,
  `impressions` int NOT NULL DEFAULT 0,
  `clicks` int NOT NULL DEFAULT 0,
  `engagements` int NOT NULL DEFAULT 0,
  `shares` int NOT NULL DEFAULT 0,
  `saves` int NOT NULL DEFAULT 0,
  `comments` int NOT NULL DEFAULT 0,
  `reach` int NOT NULL DEFAULT 0,
  `videoViews` int NOT NULL DEFAULT 0,
  `videoCompletionRate` varchar(10) DEFAULT '0',
  `ctr` varchar(10) DEFAULT '0',
  `engagementRate` varchar(10) DEFAULT '0',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
