-- Migration: Create monitored_sites table for Site Monitor feature
CREATE TABLE IF NOT EXISTS `monitored_sites` (
  `id` int AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `userId` int NOT NULL,
  `name` varchar(256) NOT NULL,
  `url` varchar(2048) NOT NULL,
  `checkIntervalSeconds` int NOT NULL DEFAULT 300,
  `accessMethod` enum('none','api','ssh','ftp','login','webhook','railway','vercel','netlify','render','heroku') NOT NULL DEFAULT 'none',
  `apiEndpoint` text,
  `apiKey` text,
  `apiHeaders` text,
  `loginUrl` text,
  `loginUsername` text,
  `loginPassword` text,
  `sshHost` varchar(512),
  `sshPort` int DEFAULT 22,
  `sshUsername` varchar(256),
  `sshPrivateKey` text,
  `platformProjectId` varchar(256),
  `platformServiceId` varchar(256),
  `platformToken` text,
  `platformEnvironmentId` varchar(256),
  `repairWebhookUrl` text,
  `repairWebhookSecret` text,
  `expectedStatusCode` int DEFAULT 200,
  `expectedBodyContains` text,
  `timeoutMs` int DEFAULT 30000,
  `followRedirects` boolean NOT NULL DEFAULT true,
  `sslCheckEnabled` boolean NOT NULL DEFAULT true,
  `performanceThresholdMs` int DEFAULT 5000,
  `alertsEnabled` boolean NOT NULL DEFAULT true,
  `alertEmail` varchar(320),
  `alertWebhookUrl` text,
  `alertAfterConsecutiveFailures` int DEFAULT 3,
  `autoRepairEnabled` boolean NOT NULL DEFAULT true,
  `isPaused` boolean NOT NULL DEFAULT false,
  `lastCheckAt` timestamp,
  `lastStatus` enum('healthy','degraded','down','error','unknown') NOT NULL DEFAULT 'unknown',
  `lastResponseTimeMs` int,
  `lastHttpStatusCode` int,
  `consecutiveFailures` int NOT NULL DEFAULT 0,
  `uptimePercent24h` varchar(8),
  `uptimePercent7d` varchar(8),
  `uptimePercent30d` varchar(8),
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
